Unit 8
nam246196/khacnam pull request #3
Opened 2020-12-04 16:09 UTC by nam246196

2020-12-04 16:21 UTC, nam246196 commented
Nguyễn Khắc Nam
REACTJS2010E
Menu : https://github.com/nam246196/khacnam/tree/unit-8/unit8/menu
Layout : https://github.com/nam246196/khacnam/tree/unit-8/unit8/single
đã làm hết.

2020-12-06 02:29 UTC, trunghongoc requested changes
1.
Phần đang ghi phải là phần description chứ không phải là comments
![image](https://user-images.githubusercontent.com/25766981/101269700-2b90b480-37a4-11eb-87d8-4f9ec2d12484.png)

2.
![image](https://user-images.githubusercontent.com/25766981/101269715-4a8f4680-37a4-11eb-9564-b5ded17b4b9d.png)
- Tại sao làm unit 8 lại có commit liên quan đến unit 7?
- Không được viết tiếng việt
- Chữ cái đầu tiên của commit (của 1 câu) phải viết hoa

3.
![image](https://user-images.githubusercontent.com/25766981/101269745-98a44a00-37a4-11eb-8689-2cce8f682a44.png)
Ở đâu ra những file linh tinh thế này


4.
![image](https://user-images.githubusercontent.com/25766981/101269760-b1146480-37a4-11eb-9176-b9a050f03630.png)

Ở đâu ra 1 đống file unit 7 thế này

5.
Quá nhiều file thừa, khoảng tầm 30 file thừa đưa vào làm PR rất rối

6.
Học lại git flow

7.



-------->
Donate 15k (quá nhiều lỗi sơ đẳng: tab)

2020-12-06 02:29 UTC, trunghongoc commented on unit6/bai1/index.html
> +        integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
Lần sau cũng link cdn bootstrap vào

2020-12-06 02:29 UTC, trunghongoc commented on unit8/menu/index.html
> +                <li><a href=""><i class="fa fa-home"></i> HOME <span>sweet home</span></a></li>
```suggestion
                <li>
                    <a href="">
                        <i class="fa fa-home"></i>
                        HOME <span>sweet home</span>
                    </a>
                </li>
```

2020-12-06 02:29 UTC, trunghongoc commented on unit8/menu/index.html
> +                <li class="active"><a href=""><i class="fa fa-edit"></i> ABOUT US <span>sweet home</span></a></li>
Enter xuống viết thành nhiều dòng, dài quá nhìn rất rối

2020-12-06 02:29 UTC, trunghongoc commented on unit8/menu/style.scss
> +                width: 300px;
Tab kiểu gì cả cây số thế này?

2020-12-06 02:29 UTC, trunghongoc commented on unit8/single/index.html
> +                                ed rcuc consequat ipsum dolor.</p>
```suggestion
                            <p>
                                Morbi in sem quis dui placetat ellentesque odio nisi euismod in haretra a ultricies in
                                diam
                                ed rcuc consequat ipsum dolor.
                            </p>
```

2020-12-06 02:29 UTC, trunghongoc commented on unit7/single/style.css
> +.wrap_main {
```suggestion
.wrap-main {
```

2020-12-06 11:52 UTC, merged